// @generated by protoc-gen-connect-es v1.1.2 with parameter "target=ts"
// @generated from file orbitdb.proto (package orbitdb, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { Empty, MethodKind } from "@bufbuild/protobuf";
import { AvailableDatabasesResponse, CloseDatabaseRequest, OpenDatabaseRequest, OpenDatabaseResponse } from "./orbitdb_pb.js";

/**
 * Define the OrbitDB service
 *
 * @generated from service orbitdb.OrbitDBService
 */
export const OrbitDBService = {
  typeName: "orbitdb.OrbitDBService",
  methods: {
    /**
     * Define the RPC methods for the OrbitDB service
     *
     * @generated from rpc orbitdb.OrbitDBService.StopService
     */
    stopService: {
      name: "StopService",
      I: Empty,
      O: Empty,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc orbitdb.OrbitDBService.AvailableDatabases
     */
    availableDatabases: {
      name: "AvailableDatabases",
      I: Empty,
      O: AvailableDatabasesResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc orbitdb.OrbitDBService.OpenDatabase
     */
    openDatabase: {
      name: "OpenDatabase",
      I: OpenDatabaseRequest,
      O: OpenDatabaseResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc orbitdb.OrbitDBService.CloseDatabase
     */
    closeDatabase: {
      name: "CloseDatabase",
      I: CloseDatabaseRequest,
      O: Empty,
      kind: MethodKind.Unary,
    },
  }
} as const;

