// @generated by protoc-gen-connect-es v1.1.2 with parameter "target=ts"
// @generated from file orbitdbrpc/v1/orbitdb.proto (package orbitdbrpc.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { AvailableDatabasesRequest, AvailableDatabasesResponse, CloseDatabaseRequest, CloseDatabaseResponse, OpenDatabaseRequest, OpenDatabaseResponse, StopServiceRequest, StopServiceResponse } from "./orbitdb_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * OrbitDB RPC service. This service is used to interact with an OrbitDB instance
 * running locally on the same machine. This allows for shared access to the same
 * OrbitDB instance from multiple clients. This service is not intended to be used
 * for remote access to an OrbitDB instance.
 *
 * @generated from service orbitdbrpc.v1.OrbitDBService
 */
export const OrbitDBService = {
  typeName: "orbitdbrpc.v1.OrbitDBService",
  methods: {
    /**
     * @generated from rpc orbitdbrpc.v1.OrbitDBService.StopService
     */
    stopService: {
      name: "StopService",
      I: StopServiceRequest,
      O: StopServiceResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc orbitdbrpc.v1.OrbitDBService.AvailableDatabases
     */
    availableDatabases: {
      name: "AvailableDatabases",
      I: AvailableDatabasesRequest,
      O: AvailableDatabasesResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc orbitdbrpc.v1.OrbitDBService.OpenDatabase
     */
    openDatabase: {
      name: "OpenDatabase",
      I: OpenDatabaseRequest,
      O: OpenDatabaseResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc orbitdbrpc.v1.OrbitDBService.CloseDatabase
     */
    closeDatabase: {
      name: "CloseDatabase",
      I: CloseDatabaseRequest,
      O: CloseDatabaseResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

